/*
 * Copyright 2025 Haseem Kheiri
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND.
 */

package com.tsh.toolkit.ai.bridge.provider.impl;

import lombok.Getter;

/**
 * Represents the complete response received from an AI language model, including both content and
 * metadata.
 *
 * <p>This class encapsulates the raw response from an AI provider, containing the generated content
 * along with optional metadata about the generation process. It serves as the standard return type
 * for AI bridge provider implementations, providing a unified interface across different AI
 * services.
 *
 * <p><strong>Response Components:</strong>
 *
 * <ul>
 *   <li><strong>Content:</strong> The actual text generated by the AI model (required)
 *   <li><strong>Metadata:</strong> Performance metrics and execution details (optional)
 * </ul>
 *
 * <p><strong>Content Format:</strong> The content field contains the raw output from the AI model,
 * which may be plain text, structured data (JSON, XML), code, or any other format depending on the
 * prompt and model capabilities. No processing or parsing is performed on this content.
 *
 * <p><strong>JSON Representation:</strong><br>
 * When received from an AI provider, the response typically has this structure:
 *
 * <pre>{@code
 * {
 *   "content":
 *   "[{\"etf_name\":\"VTI\",\"description\":\"Total market ETF\",\"reason\":\"Diversification\"}]",
 *   "metadata": {
 *     "latencyMs": 912,
 *     "inputTokens": 120,
 *     "outputTokens": 60,
 *     "finishReason": "stop"
 *   }
 * }
 * }</pre>
 *
 * <p><strong>Usage Examples:</strong>
 *
 * <pre>{@code
 * // Processing a successful response
 * AiRawResponse response = aiProvider.process(request);
 * String content = response.getContent();
 *
 * // Check if response completed successfully
 * Metadata metadata = response.getMetadata();
 * if (metadata != null && "stop".equals(metadata.getFinishReason())) {
 *     // Process complete response
 *     processGeneratedContent(content);
 * } else if (metadata != null && "length".equals(metadata.getFinishReason())) {
 *     // Handle truncated response
 *     logger.warn("Response was truncated");
 * }
 *
 * // Extract performance metrics
 * if (metadata != null && metadata.getLatencyMs() != null) {
 *     logger.info("AI response took {}ms", metadata.getLatencyMs());
 * }
 *
 * // Track token usage for billing
 * if (metadata != null) {
 *     Integer inputTokens = metadata.getInputTokens();
 *     Integer outputTokens = metadata.getOutputTokens();
 *     if (inputTokens != null && outputTokens != null) {
 *         usageTracker.recordTokens(inputTokens + outputTokens);
 *     }
 * }
 * }</pre>
 *
 * <p><strong>Error Handling:</strong> The content field should never be null, but applications
 * should be prepared to handle empty content in error scenarios. The metadata field is optional and
 * may be null if the provider doesn't supply execution details.
 *
 * <p><strong>Thread Safety:</strong> This class is immutable and thread-safe.
 *
 * @since 0.0.1-SNAPSHOT
 * @author Haseem Kheiri
 * @see AiRawRequest
 * @see Metadata
 * @see Message
 */
@Getter
public final class AiRawResponse {

  /**
   * The raw text content generated by the AI model.
   *
   * <p>This field contains the unprocessed output from the AI model exactly as received from the
   * provider. The content may be in various formats such as plain text, JSON, XML, code, or any
   * other structured format depending on the request and model capabilities.
   *
   * <p>This field should never be null, though it may be empty in error scenarios.
   */
  private final String content; // raw model output

  /**
   * Optional metadata providing performance metrics and execution details about the AI response.
   *
   * <p>The metadata includes information such as response latency, token usage counts, and the
   * reason the generation process stopped. This information is valuable for monitoring, debugging,
   * cost tracking, and performance optimization.
   *
   * <p>This field may be null if the AI provider doesn't supply execution metadata.
   */
  private final Metadata metadata; // optional

  /**
   * Constructs a new AiRawResponse with the specified content and optional metadata.
   *
   * <p>This constructor creates an immutable response object containing the AI-generated content
   * and any available execution metadata. The content represents the raw output from the AI model,
   * while the metadata provides optional performance and usage information.
   *
   * <p><strong>Parameter Handling:</strong>
   *
   * <ul>
   *   <li>Content should never be null (use empty string for error cases)
   *   <li>Metadata may be null if the provider doesn't supply execution details
   *   <li>Both parameters are stored as-is without validation or processing
   * </ul>
   *
   * @param content the raw text content generated by the AI model; should not be null
   * @param metadata optional execution metadata (latency, tokens, finish reason); may be null
   */
  public AiRawResponse(String content, Metadata metadata) {
    this.content = content;
    this.metadata = metadata;
  }
}
