<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"
>
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.tsh.toolkit</groupId>
    <artifactId>toolkit</artifactId>
    <version>${revision}</version>
  </parent>
  <artifactId>libraries</artifactId>
  <packaging>pom</packaging>
  <properties>
    <coverage.instruction.minimum>0.90</coverage.instruction.minimum>
    <coverage.branch.minimum>0.50</coverage.branch.minimum>
  </properties>
  <modules>
    <module>toolkit-core</module>
    <module>codec-core-libraries</module>
    <module>test-core</module>
    <module>file-core</module>
    <module>lock-libraries</module>
    <module>cluster-libraries</module>
    <module>rdbms-core</module>
    <module>cache-libraries</module>
    <module>ai-libraries</module>
  </modules>
</project>